### ISSUE TITLE
Merge with me? - Gnome15.org

### ISSUE THREAD

**Issue by Huskynarr** [CMoH/gnome15#1]
Hey, Gnome15.org is now my Domain. 
Can we Talk? :)

**Comment by CMoH** [comment]
Hey. What do you want to talk about?

**Comment by Huskynarr** [comment]
I want reboot gnome15.org :)

**Comment by CMoH** [comment]
Cool! I am using gnome15 on my gentoo machine, but my interest is maintaining gnome15 is limited at my own computer. I am glad someone is trying to make a more organized attempt at it.

I am unsure how to "merge" to repositories via github, but git itself should have no problems pulling changes from my repository into yours. If I find that your fork works fine on gentoo I'll change the URLs in my gentoo ebuilds to point to your fork.

Any ideas are welcome! :)

**Comment by alien2003** [comment]
Hi! I want to take a part...  I am Ubuntu and Arch user. Are you still alive guys? We need to reboot it ,really. Gnome15 is not usable on my Arch :(

**Comment by Huskynarr** [comment]
We are alive. But the last Week was the Server down. :( But now available.

**Comment by alien2003** [comment]
Check up the website. Links does not match in some places

**Comment by Huskynarr** [comment]
Unfortunately, I still have to do some things.
If you want, I can always use some help.

**Comment by alien2003** [comment]
Sure It would be great to help with this project. But really I don't have much experience with it

**Comment by Huskynarr** [comment]
Do you have Experience with web or Something?

**Comment by alien2003** [comment]
Yes I have experience with webdev but it was near year ago

**Comment by CMoH** [comment]
I'm adding a notice in my repo that people should follow https://github.com/Huskynarr/gnome15. I'm glad to see your initiative gained momentum. I'll switch to your fork asap.
