### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by alien2003** [CMoH/gnome15#2]
I want to build it on Arch. How can I build it?

And thank you very much for keeping this project alive

**Comment by CMoH** [comment]
I don't understand the question... You build it the way most linux source packages get built: configure, make, make install.

This might help: https://wiki.archlinux.org/index.php/Creating_packages

You can find more of gnome15 dependencies by taking a look at the latest ebuilds in my gentoo overlay: https://github.com/CMoH/gnome15-overlay/tree/master/app-misc/gnome15

**Comment by alien2003** [comment]
I'm new to it. I don't know how to work with GNU Autotools. Thank you anyway for your answer.
I'm just a user. Arch lacks of this package and I'm just trying to do something with it and than share with community. I'll read about autotools

**Comment by alien2003** [comment]
configure: error: g5direct driver cannot be built without libg15
Where can I get libg15?

**Comment by CMoH** [comment]
You can either skip the g15direct driver, relying only on the kernel driver, or you can find a version of libg15 customized by the author of gnome15.

As said before, my Gentoo overlay for gnome15 can help - take a look inside this file:

https://github.com/CMoH/gnome15-overlay/blob/master/dev-libs/libg15-gnome15/libg15-gnome15-1.3.0.3-r6.ebuild

Substituting ${P} with the package name+version, the SRC_URI ends up pointing to http://www.cheepee.ro/~cipi/portage/distfiles/libg15-gnome15-1.3.0.3.tar.gz

**Comment by CMoH** [comment]
Does the discussion in #3 help? See the link to the wiki page.
