### ISSUE TITLE
gnome15 should depend on dev-python/pyudev[pygobject]

### ISSUE THREAD

**Issue by netfab** [CMoH/gnome15#4]
Hi,

On my system I had dev-python/pyudev installed as dependency of another package.

In gnome15 after enabling the systray plugin for the first time I found this in my ~/.xsession-errors :

```
gnome15.g15devices - Failed to get PyUDev context, hot plugging support not available
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/gnome15/g15devices.py", line 469, in <module>
    import pyudev.glib
ImportError: No module named glib
```

gnome15 should depend on dev-python/pyudev[pygobject].

**Comment by CMoH** [comment]
Was this solved on https://github.com/Huskynarr/gnome15 ? I'll mark my repo as deprecated and migrate the gentoo overlay to build from there instead of here.
